# Generated by Django 2.2.6 on 2019-10-24 01:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_boleta', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('detalle', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
